from datetime import datetime
from sqlalchemy import Column, Integer, String, Boolean, DateTime, Float, ForeignKey, JSON, UniqueConstraint, Text
from sqlalchemy.orm import relationship
from app.database import Base
class Collection(Base):
 __tablename__='collections'; id=Column(Integer,primary_key=True); tmdb_collection_id=Column(Integer,unique=True,index=True,nullable=False); name=Column(String,nullable=False); poster_path=Column(String); backdrop_path=Column(String); overview=Column(Text); enabled=Column(Boolean,default=True); auto_add_missing=Column(Boolean,default=False); quality_profile_id=Column(Integer); root_folder_path=Column(String); sync_interval=Column(Integer,default=6); last_sync_at=Column(DateTime); next_sync_at=Column(DateTime); created_at=Column(DateTime,default=datetime.utcnow); updated_at=Column(DateTime,default=datetime.utcnow,onupdate=datetime.utcnow); movies=relationship('Movie',back_populates='collection',cascade='all, delete-orphan')
class Movie(Base):
 __tablename__='movies'; id=Column(Integer,primary_key=True); collection_id=Column(Integer,ForeignKey('collections.id',ondelete='CASCADE'),index=True); tmdb_movie_id=Column(Integer,index=True,nullable=False); title=Column(String,nullable=False); release_date=Column(String); year=Column(Integer); imdb_id=Column(String); poster_path=Column(String); backdrop_path=Column(String); overview=Column(Text); created_at=Column(DateTime,default=datetime.utcnow); updated_at=Column(DateTime,default=datetime.utcnow,onupdate=datetime.utcnow); collection=relationship('Collection',back_populates='movies'); state=relationship('MovieState',back_populates='movie',uselist=False,cascade='all, delete-orphan'); __table_args__=(UniqueConstraint('collection_id','tmdb_movie_id'),)
class MovieState(Base):
 __tablename__='movie_states'; id=Column(Integer,primary_key=True); movie_id=Column(Integer,ForeignKey('movies.id',ondelete='CASCADE'),unique=True); radarr_movie_id=Column(Integer); radarr_managed=Column(Boolean,default=False); filesystem_exists=Column(Boolean,default=False); filesystem_path=Column(String); status=Column(String,default='missing'); match_confidence=Column(Float,default=0); last_checked_at=Column(DateTime,default=datetime.utcnow); movie=relationship('Movie',back_populates='state')
class Exclusion(Base):
 __tablename__='exclusions'; id=Column(Integer,primary_key=True); collection_id=Column(Integer,ForeignKey('collections.id',ondelete='CASCADE')); tmdb_movie_id=Column(Integer); reason=Column(String); created_at=Column(DateTime,default=datetime.utcnow); __table_args__=(UniqueConstraint('collection_id','tmdb_movie_id'),)
class SyncRun(Base):
 __tablename__='sync_runs'; id=Column(Integer,primary_key=True); collection_id=Column(Integer,index=True); started_at=Column(DateTime,default=datetime.utcnow); completed_at=Column(DateTime); status=Column(String,default='queued'); movies_discovered=Column(Integer,default=0); movies_added=Column(Integer,default=0); movies_skipped=Column(Integer,default=0); movies_failed=Column(Integer,default=0); error=Column(Text)
class AuditLog(Base):
 __tablename__='audit_logs'; id=Column(Integer,primary_key=True); timestamp=Column(DateTime,default=datetime.utcnow,index=True); action=Column(String,index=True); collection_id=Column(Integer); tmdb_movie_id=Column(Integer); radarr_movie_id=Column(Integer); details=Column(JSON); result=Column(String); error_message=Column(Text)
class User(Base):
 __tablename__='users'; id=Column(Integer,primary_key=True); username=Column(String,unique=True,index=True); password_hash=Column(String); is_admin=Column(Boolean,default=True); created_at=Column(DateTime,default=datetime.utcnow); updated_at=Column(DateTime,default=datetime.utcnow,onupdate=datetime.utcnow); sessions=relationship('Session',back_populates='user',cascade='all, delete-orphan')
class Session(Base):
 __tablename__='sessions'; id=Column(Integer,primary_key=True); user_id=Column(Integer,ForeignKey('users.id',ondelete='CASCADE')); token=Column(String,unique=True,index=True); expires_at=Column(DateTime,index=True); created_at=Column(DateTime,default=datetime.utcnow); user=relationship('User',back_populates='sessions')
class Job(Base):
 __tablename__='jobs'; id=Column(Integer,primary_key=True); job_id=Column(String,unique=True,index=True); name=Column(String); status=Column(String,default='queued'); progress=Column(Integer,default=0); total_steps=Column(Integer,default=0); current_step=Column(Integer,default=0); result=Column(JSON); error=Column(Text); started_at=Column(DateTime,default=datetime.utcnow); completed_at=Column(DateTime)
